### ISSUE TITLE
How to get the each move at current board?

### ISSUE THREAD

**Issue by rockmanray** [waltheri/wgo.js#103]
I want to collect the moves from current board, and I take a try on the path object.
However, the path object contains the size of moves and variants.
To be more specific, if there's 5 moves on current board, I want to print all the coordinate of each move.
So there's might be:
1. (6,4)
2. (5,3)
3. (13,17)
4. (13,8)
5. (9,6)

If there's an appropriate way to do it?

**Comment by waltheri** [comment]
If you are interested in moves, which are currently on the board, you can use `player.kifuReader.getPosition()`. You will get `Position` object with an array representing the board position.

If you need all moves played so far, you will need to iterate `Kifu` object (`player.kifuReader.kifu`) up to current node (`player.kifuReader.node`) and extract moves from `KNode` objects.

**Comment by rockmanray** [comment]
Thanks, I just found another way to do it. I use the current node and a while loop, and climb up to its parent to get all moves.
Again, thanks for your reply.
