### ISSUE TITLE
Feature Request: Add "Export SGF-Feature"

### ISSUE THREAD

**Issue by ichderfisch** [waltheri/wgo.js#11]
It would be really nice to have an export feature in wgo.js-Player. Such a feature would be pretty neat. I know it from GoSWF, the Flash-SGF-Viewer.
See: http://www.gludion.com/go/edit-mode.html

WGo-Player already has the possibility to replay and edit the SGF-Files, but it's not possible to export variations.

Unlike in GoSWF it would be nice to have to different kind of export modes:

1. Export complete SGF including the variation (this is the same feature like in GoSWF)
2. Export Variation only. This would be pretty nice. If you are using WGo on a community website. It makes it much easier to discuss about several variations. No more need to create several SGF-Files an external SGF-Viewer and upload all one by one. Just export the SGF-Variation and copy-paste it as static wgo-layout.

An edit+export feature in combination with https://github.com/klangfarbe/Go-for-WordPress would be awesome

**Comment by shubhendusaurabh** [comment]
Hi, @waltheri Has export to SGF feature been added?
