### ISSUE TITLE
sgf player via ajax

### ISSUE THREAD

**Issue by ferlopagu** [waltheri/wgo.js#31]
Hi,before all I love this project.
I'm building a website where i can see sgf files using wgo.js, the problem comes when i using ajax.

Without using ajax:

div data-wgo="/static/{{c.partida.path}}"

Translates to

div id="wgo_0" class="wgo-player-main wgo-twocols wgo-large" data-wgo="/static/sgf/antonionu-sakunoCC3.sgf"

and it works.

Using ajax

div data-wgo='/static/"+data[i].respuestas[j].partida+"'

Translates to

div data-wgo="/static/sgf/ersev-hindoX41.sgf"

and it doesn't works.

How can i add wgo sgf player via ajax?

**Comment by waltheri** [comment]
Hi,

HTML data attributes (data-wgo) are processed after page is loaded and then they are ignored. You will probably need to load sgf with javascript. For example:

```javascript
var elem = document.getElementById("player");
var player = new WGo.BasicPlayer(elem, {
    sgfFile: "game.sgf"
});
```

Then you can use method:

```javascript
player.loadSgf("game.sgf");
```

To replace SGF in the player.

**Comment by ferlopagu** [comment]
Thank you for your quick response.

First i built some players in ajax petition:

html_player+="<div class='player'></div>";
html= //add multiple html_player 

$("#new_players").append(html);

and then, I'm trying that:

$( ".player" ).each(function() {
	var elem = $(this);
	var player= new WGo.BasicPlayer(elem, {
		sgfFile: "/static/sgf/Quentin-ersev.sgf" 
		});
	//player.loadSgf(sgf);
	console.log("SGF LOADED");
});

But i recieve:
TypeError: t.appendChild is not a function

**Comment by waltheri** [comment]
Not exactly sure what you are trying to do, but I see problem in your code - first argument of `WGo.BasicPlayer` is DOM element, you are passing jQuery object. Try this:

```javascript
$( ".player" ).each(function() {
  var player = new WGo.BasicPlayer(this, {
    sgfFile: "/static/sgf/Quentin-ersev.sgf" 
  });
});
```

**Comment by ferlopagu** [comment]
I'm doing a social network. Then when paging comments and replies of the wall, the problem was that he could not show the items via ajax from page 2.

But the problem was that, using 'this' instead of the jQuery object, everything works fine.

So thank you very much for your help, and a great job with Wgo.js
