### ISSUE TITLE
Window size responsiveness issues

### ISSUE THREAD

**Issue by yewang** [waltheri/wgo.js#32]
Using the demo player:
http://wgo.waltheri.net/demo/player/1
and playing with different window widths, I noticed the following odd behavior in the automatic player resizing.

When resizing the window over widths >643 pixels, the player is needlessly scaled down proportional to the width of the window, even though there is still white space to the right of the player. This effectively maintains a large portion of whitespace to the right of the player, thus not fully utilizing the width of the screen, which seems quite arbitrary given that the sizing does not seem to be dependent on another factor, such as the vertical height of the screen.

It seems that the comments panel is not shown for some window widths. Oddly, for >932 pixels wide  the comments panel is shown, for 932 to 644 pixels wide the comments panel is not shown, for 643 to 566 pixels wide the comments panel is shown, and >566 pixels the comments panel is not shown again. I think this alternating behavior has to do with how the player switches between vertical and horizontal layouts while resizing.

**Comment by waltheri** [comment]
Hi,
I think that resizing of the player works as it should. In the demo, the player occupies 60% of the window width in the landscape mode and 100% width in the portrait mode. It is directly defined in that demo. See:

```css
.player {
  width: 60%;
  margin: 0;
}

@media screen and (orientation:portrait) {
  .player {
    width: 100%;
  }
}
```

Anyway thanks for the message.

**Comment by yewang** [comment]
Sorry about that. I was mistaken about the intended behavior on the player resizing.

Is the behavior of hiding the comments for some window widths also intended? If so, how would one configure always showing the comments?
