### ISSUE TITLE
how can I replace the board_click_default ?

### ISSUE THREAD

**Issue by tianzuo** [waltheri/wgo.js#38]
Hi, waltheri,
thanks for your wgo.js, it's the best go board I found. I'm trying to use it in my project, but I miss a problem. I need to replace board_click_default function, but I don't know how to do it outside the wgo.js. Is that any hook to do this? thanks!

**Comment by waltheri** [comment]
Hi,
I am afraid that you will have to override method `Player.prototype.init`, second option is to extend class `Player` or `BasicPlayer` and implement method `init`.

**Comment by tianzuo** [comment]
thanks！
