### ISSUE TITLE
Interface definition needed

### ISSUE THREAD

**Issue by d180cf** [waltheri/wgo.js#47]
Since JS lacks the notion of types and interfaces, it's pretty hard to grasp the structure of the API. This could be solved by either jsdoc-style comments with a jsdoc parser or with a separate interface definition file. I've started writing [one](https://github.com/d180cf/tsumego.js/blob/wgo/wgo/wgo.d.ts) for wgo, but obviously I won't be able to write it accurately and I can't write meaningful comments. If you could write one, that would be very helpful. Here is an excerpt from my file:

```ts
    interface BasicPlayer {
        new (target: HTMLElement, options: BasicPlayer.Options): BasicPlayer;

        board: Board;
        kifuReader: KifuReader;

        next(nodeIndex: number): void;
        previous(): void;
        update(): void;
        /** Shows/hides side goban labels. */
        setCoordinates(value: boolean): void;
    }
```

**Comment by waltheri** [comment]
I will be doing it in WGo.js 3, which I will start to develop soon.
