### ISSUE TITLE
KifuReader::allowIllegalMoves doesn't work

### ISSUE THREAD

**Issue by d180cf** [waltheri/wgo.js#48]
It seems to set the `repeating` member in a wrong place. I have [fixed](https://github.com/d180cf/tsumego.js/commit/a95dd83d69a79c774ba0c7ad1904a51be931d3df) this in my local copy of wgo and the fix seems to work: it lets me repeat previous positions. Could you take a look at the fix and check whether it makes sense?

**Comment by waltheri** [comment]
I don't see any error. There is even [test](https://github.com/waltheri/wgo.js/blob/master/test/test04.html) for that. What doesn't work?

**Comment by d180cf** [comment]
After this method is invoked, repetitions are still not allowed.

**Comment by waltheri** [comment]
I updated *test04.html* with a repetition test and it seems to work.

**Comment by d180cf** [comment]
Hmm.. that allowIllegalMoves function assigns something to `this.repeating` but where is this value read then?
