### ISSUE TITLE
How to display stone number?

### ISSUE THREAD

**Issue by dongww** [waltheri/wgo.js#51]
How to display stone number?

Thank you!

**Comment by waltheri** [comment]
Hi,
I'm not sure, what do you mean. Do you want to display move numbers on stones, or count of black and white stones, or something else?

**Comment by dongww** [comment]
yes, how to display move numbers.

**Comment by waltheri** [comment]
Currently there is no option for it in the player. However with a little bit of programming you can make it.

At first you will need board drawing API methods ``WGo.Board.prototype.addObject(obj)`` and ``WGo.Board.prototype.removeObject(obj)``, then you will add ``update`` event listener to the ``WGo.BasicPlayer`` object, which you will use for drawing of move numbers. Simple example is here:

``` javascript
var player = new WGo.BasicPlayer(document.querySelector("#wgo_wrapper"), {
	sgfFile: "game.sgf", // some sgf file
	markLastMove: false // disable last move marker
});

// storage for move markers
var number_markers = [];

player.addEventListener("update", function(e) {
	// this function will be executed after every move

	var marker;
	if(e.path.m < number_markers.length) {
		// remove old move numbers
		for(var i = e.path.m; i < number_markers.length; i++) {
			player.board.removeObject(number_markers[i]);
		}
		number_markers.splice(e.path.m);
	}
	else if(e.node.move && !e.node.move.pass) {
		// add current move marker
		marker = {x: e.node.move.x, y: e.node.move.y, type: "LB", text: e.path.m};
		number_markers.push(marker);
		player.board.addObject(marker);
	}
});
```

This isn't fully working example. It doesn't work with fast forward. But I believe it won't be so difficult to adjust it.

**Comment by dongww** [comment]
Thank you very much!
