### ISSUE TITLE
On ipad web browser, click on the board, there will be flashing.

### ISSUE THREAD

**Issue by dongww** [waltheri/wgo.js#53]
On ipad web browser, click on the board, there will be flashing.

**Comment by waltheri** [comment]
Unfortunately I don't own iPad, so I can't test it and solve it.

**Comment by dongww** [comment]
I solved this problem.

~~~ css
.container {
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
~~~

**Comment by waltheri** [comment]
Let me know if it is good now.
