### ISSUE TITLE
How do I get an event from wgo that a move's been played?

### ISSUE THREAD

**Issue by d180cf** [waltheri/wgo.js#55]
In wgo there is an editing mode in which I can add stones. Is there a way to somehow add a listener to wgo and make it invoke that listener whenever a stone is added?

I need this feature to simplify testing the tsumego solver: if the solver's found a solution, it would be convenient to just play moves in wgo and let the solver play a reply.

**Comment by waltheri** [comment]
Unfortunately there isn't event for it. However I think you can use `update` event of the player. Whenever you add stone with `WGo.Player.Editable`, the new kifu node gets attribute `_edited = true`. Update callback is invoked after every move and if a node in its argument will contain this attribute, you will know, that you added stone. Then you just remove `_edited` property from the node for the future.
