### ISSUE TITLE
How to remove stone and save game with sgf

### ISSUE THREAD

**Issue by lifengbo** [waltheri/wgo.js#63]
When i use the WGO, i have 2 question,

1.  I want to save sgf file when complete go game, I use the function:
```javascript
var sgf = player.kifuReader.kifu.toSgf();
```
  
  this usage is correctly?

2.I'm not familiar with js. I use the follewing method to remove stone:
```javascript
var removeStone = {x : x, y: y, c:this.player.kifuReader.game.position.get(x, y)};
board.removeObject(removeStone);
this.player.kifuReader.game.position.set(x,y, 0);
```

it's work, but when i store the sgf like :

```javascript
var sgf = player.kifuReader.kifu.toSgf();
```
This sgf file is incorrect, can you provide a example for remove stone and save the go game for sgf, thinks.

**Comment by waltheri** [comment]
Hi,

question number 1 - this is ok, however `player.kifu.toSgf()` should work as well.

Number 2 - it depends what you mean by "remove stone". Generally with:

``` javascript
board.removeObject(removeStone);
```

you just remove stone from graphical board. On the other hand with:

``` javascript
this.player.kifuReader.game.position.set(x,y, 0);
```

you remove stone from current "virtual" position. However none of this changes the kifu whatsoever. So you want to change the kifu object to produce different SGF. To remove stone in certain point in the time you can add a setup node - for example:

``` javascript
var setupNode = new WGo.KNode();
setupNode.addSetup({x:1, y:1}); // setup property to remove stone on B18
player.kifuReader.node.insertAfter(setupNode); // add new node after current node
player.next(); // see changes
```

This will add to SGF file node with [AE](http://www.red-bean.com/sgf/properties.html#AE) property. Or maybe you want to remove the whole move(node). This is simpler:

``` javascript
player.kifuReader.node.remove();
```

*It seems there is a bug in remove method, so it may nor work properly, but SGF export should work.*

**Comment by lifengbo** [comment]
Thanks，very nice code!
