### ISSUE TITLE
Unminified wgo.player.js

### ISSUE THREAD

**Issue by blackslate** [waltheri/wgo.js#68]
## Solved
**https://github.com/waltheri/wgo.js/blob/master/build.sh**

Is there an unminified version of `wgo.player.js` available?

I am getting a number of errors where a black overlay appears and says...

> TypeError
> 
> this.setMessage is not a function

... or ...

> InvalidMoveError
> 
> Invalid move in kifu detected. Trying to play black move on Q12, but this move is a suicide., but this position already occured.

... (when this is not in fact the case). As far as I can tell the code that triggers this is in `wgo.player.min.js`, so it would be good to have an unminified version to help track down the cause.

**Comment by UFO-101** [comment]
Hi I am facing the same error. Did you find why you were getting an InvalidMoveError?

Update: my issue was that I was using a different rule set fixed with:
```
new window.WGo.BasicPlayer(goBoardDiv, {
    sgfFile: sgfPath,
    allowIllegalMoves: true,
});
```

**Comment by UFO-101** [comment]
As you can see in [build.sh](https://github.com/waltheri/wgo.js/blob/master/build.sh) wgo.player.min.js is a combination of:
```
kifu.js
sgfparser.js
player.js
basicplayer.js
basicplayer.component.js
basicplayer.infobox.js
basicplayer.commentbox.js
basicplayer.control.js
player.editable.js
scoremode.js
player.permalink.js
```
(in that order)
