### ISSUE TITLE
Territory counting?

### ISSUE THREAD

**Issue by gamecubate** [waltheri/wgo.js#69]
It seems as though WGo has no territory-counting capabilities, an essential for scoring of games. Is this functionality present somewhere although not documented? Thanks in advance.

**Comment by waltheri** [comment]
There is score counting mode, included in default player.

**Comment by gamecubate** [comment]
Ah I see. I created my own UI and player (SVG, d3 based), using WGo.Game as its engine. This explains why I had missed it.

I think a case can be made for integration of such a feature into WGo.Game. What do you think? If OK, I can maybe attempt a branch and send in a PR once done.

**Comment by waltheri** [comment]
I would prefer to generalize [scoremode.js](https://github.com/waltheri/wgo.js/blob/master/wgo/scoremode.js), so it could be used independently of WGo board and player, but I wouldn't merge it with WGo.Game for now. You can try it.

Btw. is your SVG board public? I am looking for inspiration for next version of [WGo](https://github.com/waltheri/wgo.js/tree/dev).

**Comment by gamecubate** [comment]
I could make it public. i hadn't thought about it as I am still very much in prototyping mode right now. I have doubts it will be of much use to others as what i am developing is rather toy like. will send screenshot shortly.

**Comment by gamecubate** [comment]
I've put my client (of your game engine) project on standby pending closing of other urgent project. Will eventually resume and send link to SVG front-end source.

**Comment by gamecubate** [comment]
This issue is getting old and I've switched to ClojureScript+React for all (personal) projects. Sharing the code for an SVG rendering of the Go board would be useless in the scope of your project. Closing issue. Thanks for this engine!
