### ISSUE TITLE
Handicap stones not displayed?

### ISSUE THREAD

**Issue by nerai** [waltheri/wgo.js#72]
I seem to have trouble displaying SGF files which use handicap stones, as saved by e.g. cgoban3.

The handicap stones are not displayed. I have not checked if they are completely missing or just invisible.

If handicap games are supposed to be working, I can add an example of an SGF file displaying the faulty behavior here.

**Comment by waltheri** [comment]
Please show me the sgf.

**Comment by nerai** [comment]
Example:

    (;GM[1]FF[4]SZ[19]KM[0.50]RU[Japanese]ST[2]HA[2]AB[pd][dp];W[pp];B[dd];W[jc];B[nq];W[lp];B[no];W[pn];B[pr];W[qq];B[jp];W[mq];B[op];W[ln];B[nm];W[qk];B[qr];W[rr];B[pq];W[qp];B[kq];W[nr];B[rs];W[rq];B[pl];W[ql];B[jn];W[ll];B[nk];W[lj];B[pm];W[qm];B[km];W[on];B[nn];W[lm];B[ni];W[fq];B[hq];W[cq];B[dq];W[cp];B[co];W[cr];B[do];W[dr];B[dj];W[gq];B[gn];W[ch];B[lh];W[jl];B[dh];W[dg];B[eh];W[io];B[jo];W[hm];B[hp];W[cj];B[ck];W[ci];B[dk];W[kh];B[kg];W[li];B[mh];W[jh];B[eg];W[df];B[jg];W[hh];B[ig];W[hj];B[be];W[bf];B[ce];W[ef];B[hg];W[gh];B[fc];W[gm];B[cf];W[cg];B[gg];W[fn];B[lr];W[mr];B[fo];W[go];B[gp];W[ed];B[ec];W[fg];B[ff];W[bk];B[bl];W[aj];B[fh];W[ag];B[al])

**Comment by nerai** [comment]
Friendly asking of there are any updates on this?

**Comment by waltheri** [comment]
Sorry I forgot this. However I checked it (in demo1.html) and it seems to work, handicap stones are displayed. Please send me site with WGo player, where it doesn't work.

**Comment by nerai** [comment]
I've prepared a test site at https://kyudan.net/estimate_debug/

It seems the problem is caused by using the Javascript version with the "move" field set. Removing that line makes the handicap stones appear.

**Comment by waltheri** [comment]
Sorry for delayed answer - I have feeling I have fixed this problem already. Try to use the newest version of WGo, which is in this repository.

**Comment by nerai** [comment]
Thank you, I have tried both wgo.js and wgo.min.js at https://kyudan.net/estimate_debug/index_1

Both *work as intended*.

Their version number is the same as the broken version (2.0), so maybe it should be increased. Thank you very much for your help troubleshooting and your helpful library.
